title: RoomMatch
description: A roommate matching platform for UH MƒÅnoa students
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/roommatch-uhm/roommatch-uhm.github.io
gems:
  - jekyll-mentions